DROP TABLE IF EXISTS tblSkill;
DROP TABLE IF EXISTS tblUser;
CREATE TABLE tblUser
(
    id    INTEGER      NOT NULL PRIMARY KEY AUTOINCREMENT,
    name  VARCHAR(100) NOT NULL,
    email VARCHAR(100) NULL,
    phone VARCHAR(100)
);

CREATE TABLE tblSkill
(
    id    INTEGER      NOT NULL PRIMARY KEY AUTOINCREMENT,
    name  VARCHAR(100) NOT NULL,
    level INT          NOT NULL DEFAULT 0
);
